#!/usr/bin/env bash

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

dconf reset -f /org/gnome/shell/extensions/paperwm/
cat "$SCRIPTS_DIR/settings" | dconf load /org/gnome/shell/extensions/paperwm/
