#! /usr/bin/env bash

# if command -v systemd-detect-virt >/dev/null; then
#   if systemd-detect-virt --quiet; then
#     exit 0
#   fi
# fi

is_any_running() {
  pgrep -f "$1" >/dev/null ||
    systemctl list-units --quiet --type=service | grep -q "^$1" ||
    systemctl --user list-units --quiet --type=service | grep -q "^$1"
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

is_running() {
  pgrep -xu "$USER" "$1" >/dev/null || systemctl --user is-active --quiet "$1"
}

if [[ "$XDG_CURRENT_DESKTOP" == *"Hyprland"* ]] && has_cmd hypridle; then
  hypridle \
    --general lock_cmd="bash -c 'scripts/lock'" \
    --listener timeout=240 on-timeout="bash -c 'scripts/lock'" \
    --listener timeout=300 on-timeout="bash -c 'scripts/monitor off'" \
    --listener on-resume="bash -c 'scripts/monitor on'" \
    --listener timeout=600 on-timeout="systemctl suspend"
elif [[ "$XDG_CURRENT_DESKTOP" == *"mango"* ]] ||
  [[ "$XDG_CURRENT_DESKTOP" == *"niri"* ]] ||
  [[ "$XDG_CURRENT_DESKTOP" == *"sway"* ]]; then
  has_cmd swayidle || {
    echo "swayidle not found" >&2
    exit 1
  }
  swayidle -w \
    timeout 240 'bash -c "scripts/lock"' \
    timeout 300 'bash -c "scripts/monitor off"' \
    resume 'bash -c "scripts/monitor on"'
  # timeout 600 'systemctl suspend'
else
  echo "No compatible compositor or idle manager found" >&2
  exit 1
fi
